version: "3"

services:
  localstack:
    image: localstack/localstack-full
    ports:
      - "4565-4576:4565-4576"
    environment:
      - SERVICES=sns,sqs,cloudformation,iam,lambda,s3
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/private${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
