Parameters:

  ProjectName:
    Type: String
    Default: mystack
    Description: Project name

  BucketName:
    Type: String
    Default: mybucket
    Description: Project bucket's name


Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowSSLRequestsOnly"
            Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}"
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': false
  Sqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref ProjectName
      MessageRetentionPeriod: 86400
      VisibilityTimeout: 30
      ReceiveMessageWaitTimeSeconds: 10
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SqsDLQ.Arn
        maxReceiveCount: 2

  SqsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-DLQ"
      MessageRetentionPeriod: 1209600

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt Sqs.Arn
      TopicArn: !Ref snsTopicOrigin

  snsTopicOrigin:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub "${ProjectName}"
      TopicName: topic-origin

  snsTopicDestination:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub "${ProjectName}"
      TopicName: topic-destination